### ISSUE TITLE
Allow reusing scoped clients setup in symfony framework bundle

### ISSUE THREAD

**Issue by bendavies** [mtarld/api-platform-ms-bundle#80]
Hi there,
In the symfony framework bundle, you can setup clients like so:

```yaml
framework:
    http_client:
        default_options:
            timeout: 5

        scoped_clients:
            foo.client:
                base_uri: 'https://foo'
```

if would then be nice if these are reusable by this bundle:

```yaml
api_platform_ms:
    name: app
    microservices:
        foo:
           http_client: foo.client
           format: jsonhal
```

This would be good, as at the moment, this bundle does not allow you to configure all the [options](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Contracts/HttpClient/HttpClientInterface.php#L26) available on the http client, while implementing the above would allow it, as you'd just define them in the framework bundle.

for example, if I want to configure a `timeout` for a particular microservice, which is currently not possible with this bundle.

What do you think?

Thanks!
